<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gallery" nsURI="http://gallery/1.0" nsPrefix="gallery">
  <eClassifiers xsi:type="ecore:EClass" name="PictureCollection" abstract="true" eSuperTypes="#//PathElement">
    <eOperations name="getPictures" upperBound="-1" eType="#//Picture"/>
    <eOperations name="getSubCollections" upperBound="-1" eType="#//PictureCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superCollection" eType="#//RealPictureCollection"
        eOpposite="#//RealPictureCollection/subCollections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Picture" abstract="true" eSuperTypes="#//PathElement">
    <eOperations name="getMetadata" eType="#//Metadata"/>
    <eOperations name="getHash" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collection" lowerBound="1"
        eType="#//RealPictureCollection" eOpposite="#//RealPictureCollection/pictures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealPicture" eSuperTypes="#//Picture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedBy" upperBound="-1"
        eType="#//LinkedPicture" eOpposite="#//LinkedPicture/realPicture"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" eType="#//Metadata"
        containment="true" eOpposite="#//Metadata/picture"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hash" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkedPicture" eSuperTypes="#//Picture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realPicture" lowerBound="1"
        eType="#//RealPicture" eOpposite="#//RealPicture/linkedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathElement" abstract="true">
    <eOperations name="getFullPath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getRelativePath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PictureLibrary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseCollection" lowerBound="1"
        eType="#//RealPictureCollection" containment="true" eOpposite="#//RealPictureCollection/library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metadata">
    <eStructuralFeatures xsi:type="ecore:EReference" name="picture" lowerBound="1"
        eType="#//RealPicture" eOpposite="#//RealPicture/metadata"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="landscape" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="created" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="camera" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealPictureCollection" eSuperTypes="#//PictureCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedBy" upperBound="-1"
        eType="#//LinkedPictureCollection" eOpposite="#//LinkedPictureCollection/realCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" eType="#//PictureLibrary"
        eOpposite="#//PictureLibrary/baseCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pictures" upperBound="-1"
        eType="#//Picture" containment="true" eOpposite="#//Picture/collection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCollections" upperBound="-1"
        eType="#//PictureCollection" containment="true" eOpposite="#//PictureCollection/superCollection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkedPictureCollection" eSuperTypes="#//PictureCollection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realCollection" lowerBound="1"
        eType="#//RealPictureCollection" eOpposite="#//RealPictureCollection/linkedBy"/>
  </eClassifiers>
</ecore:EPackage>
